[package]
name = "helloworld"
version = "0.1.0"
authors = ["Oasis Labs <feedback@oasislabs.com>"]
edition = "2018"
publish = false

[dependencies]
mantle = "0.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
mantle-test = "0.2"
